apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  labels: 
    app: api
    system: backend
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: api
    system: backend
  ports:
  - protocol: {{ .Values.api.service.protocol }}
    port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}