apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.deployment.name }}
  labels: 
    app: api
    system: backend
spec:
  replicas: {{ .Values.api.replicaCount }}
  strategy: 
    type: {{ .Values.app.deployment.strategyType }}
    rollingUpdate:
      maxUnavailable: {{ .Values.app.deployment.maxUnavailable }}
  selector:
    matchLabels:
      app: api
      system: backend
  template:
    metadata:
      labels:
        app: api
        system: backend
    spec:
      containers:
      - name: {{ .Values.api.image.name }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        ports:
        - containerPort: {{ .Values.api.image.containerPort }}