
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        {{- range $name, $paths := .Values.app.ingress.paths }}
        {{- range $key, $value := $paths }}
        - path: {{ $value.path }}
          backend:
            serviceName: {{ $value.serviceName }}
            servicePort: {{ $value.servicePort }}
        {{- end }}
        {{- end }}
