apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-mvc-k8s-deployment
spec:
  selector:
    matchLabels:
      app: dotnet-mvc-k8s
  replicas: 2 
  template: 
    metadata:
      labels:
        app: dotnet-mvc-k8s
    spec:
      containers:
      - name: dotnet-mvc-k8s
        image: sourcewalker/dotnet-mvc-k8s:firsttry
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: dotnet-mvc-k8s-service
spec:
 type: NodePort
 selector:
   app: dotnet-mvc-k8s
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 31000
 selector:
   app: dotnet-mvc-k8s